# Generated by Django 4.2.29 on 2026-03-26 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Stock Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(choices=[('each', 'Each'), ('bottle', 'Bottle'), ('can', 'Can'), ('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('litre', 'Litre (L)'), ('ml', 'Millilitre (ml)'), ('case', 'Case'), ('box', 'Box'), ('bag', 'Bag'), ('roll', 'Roll'), ('portion', 'Portion')], default='each', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('par_level', models.DecimalField(decimal_places=2, default=0, help_text='Ideal stock level — what should be on shelf at start of day', max_digits=10)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, help_text='Trigger reorder when stock falls below this level', max_digits=10)),
                ('reorder_qty', models.DecimalField(decimal_places=2, default=0, help_text='Standard quantity to order when reorder is triggered', max_digits=10)),
                ('avg_daily_usage', models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated average daily usage from stock counts', max_digits=10)),
                ('par_coverage_days', models.PositiveIntegerField(default=3, help_text='How many days of stock PAR should cover (e.g. 3 = 3-day buffer)')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='stock.stockcategory')),
                ('department', models.ForeignKey(blank=True, help_text='Which department manages this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='accounts.department')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('delivery', 'Delivery / Received'), ('usage', 'Usage / Consumed'), ('wastage', 'Wastage / Spoilage'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Manual Adjustment'), ('return', 'Return to Supplier')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='Invoice number, supplier name, reason, etc.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='accounts.department')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock.stockitem')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='accounts.outlet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_locations', to='accounts.department')),
                ('outlet', models.ForeignKey(blank=True, help_text='Which restaurant this storage location belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_locations', to='accounts.outlet')),
            ],
            options={
                'ordering': ['outlet__order', 'name'],
                'unique_together': {('outlet', 'name')},
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='stock.stocklocation'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='outlet',
            field=models.ForeignKey(blank=True, help_text='Which restaurant this item belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='accounts.outlet'),
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateField(default=django.utils.timezone.now)),
                ('shift', models.CharField(choices=[('opening', 'Opening'), ('closing', 'Closing'), ('mid', 'Mid-shift')], default='closing', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to='accounts.department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='stock.stocklocation')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to='accounts.outlet')),
            ],
            options={
                'ordering': ['-count_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_qty', models.DecimalField(decimal_places=2, default=0, help_text='Stock level expected based on last count + deliveries - usage', max_digits=10)),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, help_text='counted - expected', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock.stockcount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_lines', to='stock.stockitem')),
            ],
            options={
                'ordering': ['item__category__name', 'item__name'],
                'unique_together': {('count', 'item')},
            },
        ),
    ]
