# Generated by Django 4.2.29 on 2026-03-30 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('opening', 'Opening Duties'), ('foh', 'Front of House'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('closing', 'Closing Procedure'), ('cleaning', 'Cleaning & Maintenance'), ('meetings', 'Meetings'), ('other', 'Other')], default='other', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('all_managers_access', models.BooleanField(default=True)),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='assigned_forms', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Which department this checklist belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='accounts.department', verbose_name='Department')),
                ('outlet', models.ForeignKey(blank=True, help_text='Which restaurant this form belongs to (blank = all outlets)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_templates', to='accounts.outlet', verbose_name='Outlet')),
            ],
            options={
                'verbose_name': 'Form Template',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('full', 'Full Day')], default='day', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Overall notes for this submission')),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('completed_items', models.PositiveIntegerField(default=0)),
                ('no_responses', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='accounts.department')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='forms_builder.formtemplate')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='accounts.outlet')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Submission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='forms_builder.formtemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500)),
                ('response_type', models.CharField(choices=[('yes_no', 'Yes / No'), ('text', 'Text Input'), ('number', 'Number'), ('choice', 'Multiple Choice')], default='yes_no', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('requires_comment_on_no', models.BooleanField(default=True, help_text='If Yes/No and answered No, require explanation')),
                ('requires_image_on_no', models.BooleanField(default=False, help_text='If answered No, allow image upload')),
                ('choices_text', models.TextField(blank=True, help_text='Comma separated choices for multiple choice type')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='forms_builder.formsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True, help_text='Explanation, especially required on No responses')),
                ('image', models.ImageField(blank=True, null=True, upload_to='responses/%Y/%m/')),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='forms_builder.checklistitem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms_builder.formsubmission')),
            ],
            options={
                'ordering': ['item__order'],
                'unique_together': {('submission', 'item')},
            },
        ),
    ]
