# Generated by Django 4.2.29 on 2026-04-24 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(help_text='Short unique key, e.g. opening, bar, kitchen', unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Form Category',
                'verbose_name_plural': 'Form Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='formtemplate',
            options={'ordering': ['category__name', 'name'], 'verbose_name': 'Form Template'},
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a category — manage categories from Form Categories in the sidebar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='forms_builder.formcategory', verbose_name='Category'),
        ),
    ]
